name: Tamil Sangam Of Central Indiana
favicon: null
layout_spectrum: 1
typography_spectrum: 0.48607
title: Indy Tamil Sangam
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3b2313'
    - '#ffffff'
    - '#d1bfaa'
    - '#8b6642'
    - '#0f7abd'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    item: 4f71053d-5245-4f1c-a6f1-0741903999af
    url: null
