name: Tamil Sangam Of Central Indiana
favicon: null
layout_spectrum: 0.8
title: Indy Tamil Sangam
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3b2313'
    - '#ffffff'
    - '#d1bfaa'
    - '#8b6642'
    - '#0f7abd'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    item: null
    url: null
